name = "jkanimeflv"
compatibility_date = "2024-01-15"
pages_build_output_dir = ".next"

# Build configuration
[build]
command = "npm run build:cloudflare"
cwd = "."

[env.production]
name = "jkanimeflv"

[env.preview]
name = "jkanimeflv-preview"

# Environment variables for Cloudflare Pages
[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://jkanimeflv.com"
NEXT_PUBLIC_API_BASE_URL = "https://api-jk.funnyu.xyz"
USE_MOCK_API = "false"

[env.preview.vars]
NODE_ENV = "development"
NEXT_PUBLIC_SITE_URL = "https://jkanimeflv-preview.pages.dev"
NEXT_PUBLIC_API_BASE_URL = "https://api-jk.funnyu.xyz"
USE_MOCK_API = "true"